# Generated by Django 2.2.16 on 2022-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateTimeField(verbose_name='Дата выхода'),
        ),
    ]
