# Generated by Django 2.2.16 on 2022-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221106_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
