# Generated by Django 2.2.16 on 2022-11-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
