# Generated by Django 2.2.16 on 2022-11-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20221106_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
