# Generated by Django 2.2.16 on 2022-11-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20221106_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
