# Generated by Django 2.2.16 on 2022-11-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_review_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
    ]
