# Generated by Django 2.2.16 on 2022-11-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20221106_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
    ]
