# Generated by Django 2.2.16 on 2022-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_auto_20221107_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
